// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/ExcelFileTransfer.proto

package com.attackt.logivisual.protobuf;

public final class ExcelFileTransfer {
  private ExcelFileTransfer() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UIDOrBuilder extends
          // @@protoc_insertion_point(interface_extends:UID)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
    getUidBytes();
  }
  /**
   * Protobuf type {@code UID}
   */
  public  static final class UID extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:UID)
          UIDOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use UID.newBuilder() to construct.
    private UID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UID() {
      uid_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UID(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_UID_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_UID_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
    getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.UID)) {
        return super.equals(obj);
      }
      com.attackt.logivisual.protobuf.ExcelFileTransfer.UID other = (com.attackt.logivisual.protobuf.ExcelFileTransfer.UID) obj;

      boolean result = true;
      result = result && getUid()
              .equals(other.getUid());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.attackt.logivisual.protobuf.ExcelFileTransfer.UID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UID}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:UID)
            com.attackt.logivisual.protobuf.ExcelFileTransfer.UIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_UID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_UID_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.Builder.class);
      }

      // Construct using com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_UID_descriptor;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.UID getDefaultInstanceForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.getDefaultInstance();
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.UID build() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.UID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.UID buildPartial() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.UID result = new com.attackt.logivisual.protobuf.ExcelFileTransfer.UID(this);
        result.uid_ = uid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.UID) {
          return mergeFrom((com.attackt.logivisual.protobuf.ExcelFileTransfer.UID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.attackt.logivisual.protobuf.ExcelFileTransfer.UID other) {
        if (other == com.attackt.logivisual.protobuf.ExcelFileTransfer.UID.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.UID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.attackt.logivisual.protobuf.ExcelFileTransfer.UID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
      getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {

        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        uid_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:UID)
    }

    // @@protoc_insertion_point(class_scope:UID)
    private static final com.attackt.logivisual.protobuf.ExcelFileTransfer.UID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.attackt.logivisual.protobuf.ExcelFileTransfer.UID();
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.UID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UID>
            PARSER = new com.google.protobuf.AbstractParser<UID>() {
      public UID parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new UID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UID> getParserForType() {
      return PARSER;
    }

    public com.attackt.logivisual.protobuf.ExcelFileTransfer.UID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseRequestOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ParseRequest)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
    getUidBytes();

    /**
     * <pre>
     * excel文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     * excel文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    com.google.protobuf.ByteString
    getPathBytes();

    /**
     * <pre>
     * 密码，无则为空''
     * </pre>
     *
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();
    /**
     * <pre>
     * 密码，无则为空''
     * </pre>
     *
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString
    getPasswordBytes();

    /**
     * <pre>
     * 预留参数: 文件地址的访问形式
     * </pre>
     *
     * <code>int32 access = 4;</code>
     */
    int getAccess();
  }
  /**
   * Protobuf type {@code ParseRequest}
   */
  public  static final class ParseRequest extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:ParseRequest)
          ParseRequestOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ParseRequest.newBuilder() to construct.
    private ParseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseRequest() {
      uid_ = "";
      path_ = "";
      password_ = "";
      access_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            case 32: {

              access_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
    getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * excel文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * excel文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public com.google.protobuf.ByteString
    getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;
    /**
     * <pre>
     * 密码，无则为空''
     * </pre>
     *
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 密码，无则为空''
     * </pre>
     *
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString
    getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESS_FIELD_NUMBER = 4;
    private int access_;
    /**
     * <pre>
     * 预留参数: 文件地址的访问形式
     * </pre>
     *
     * <code>int32 access = 4;</code>
     */
    public int getAccess() {
      return access_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
      }
      if (access_ != 0) {
        output.writeInt32(4, access_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
      }
      if (access_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(4, access_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest)) {
        return super.equals(obj);
      }
      com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest other = (com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest) obj;

      boolean result = true;
      result = result && getUid()
              .equals(other.getUid());
      result = result && getPath()
              .equals(other.getPath());
      result = result && getPassword()
              .equals(other.getPassword());
      result = result && (getAccess()
              == other.getAccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (37 * hash) + ACCESS_FIELD_NUMBER;
      hash = (53 * hash) + getAccess();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ParseRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ParseRequest)
            com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.Builder.class);
      }

      // Construct using com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";

        path_ = "";

        password_ = "";

        access_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseRequest_descriptor;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest getDefaultInstanceForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.getDefaultInstance();
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest build() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest buildPartial() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest result = new com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest(this);
        result.uid_ = uid_;
        result.path_ = path_;
        result.password_ = password_;
        result.access_ = access_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest) {
          return mergeFrom((com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest other) {
        if (other == com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        if (other.getAccess() != 0) {
          setAccess(other.getAccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
      getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {

        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * excel文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * excel文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public com.google.protobuf.ByteString
      getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * excel文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPath(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * excel文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder clearPath() {

        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * excel文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPathBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        path_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <pre>
       * 密码，无则为空''
       * </pre>
       *
       * <code>string password = 3;</code>
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 密码，无则为空''
       * </pre>
       *
       * <code>string password = 3;</code>
       */
      public com.google.protobuf.ByteString
      getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 密码，无则为空''
       * </pre>
       *
       * <code>string password = 3;</code>
       */
      public Builder setPassword(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码，无则为空''
       * </pre>
       *
       * <code>string password = 3;</code>
       */
      public Builder clearPassword() {

        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 密码，无则为空''
       * </pre>
       *
       * <code>string password = 3;</code>
       */
      public Builder setPasswordBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        password_ = value;
        onChanged();
        return this;
      }

      private int access_ ;
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 4;</code>
       */
      public int getAccess() {
        return access_;
      }
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 4;</code>
       */
      public Builder setAccess(int value) {

        access_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 4;</code>
       */
      public Builder clearAccess() {

        access_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ParseRequest)
    }

    // @@protoc_insertion_point(class_scope:ParseRequest)
    private static final com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest();
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseRequest>
            PARSER = new com.google.protobuf.AbstractParser<ParseRequest>() {
      public ParseRequest parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParseRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseRequest> getParserForType() {
      return PARSER;
    }

    public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ParseResultOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ParseResult)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    java.lang.String getUid();
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    com.google.protobuf.ByteString
    getUidBytes();

    /**
     * <pre>
     * 结果json文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    java.lang.String getPath();
    /**
     * <pre>
     * 结果json文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    com.google.protobuf.ByteString
    getPathBytes();

    /**
     * <pre>
     * 预留参数: 文件地址的访问形式
     * </pre>
     *
     * <code>int32 access = 3;</code>
     */
    int getAccess();
  }
  /**
   * Protobuf type {@code ParseResult}
   */
  public  static final class ParseResult extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:ParseResult)
          ParseResultOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ParseResult.newBuilder() to construct.
    private ParseResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ParseResult() {
      uid_ = "";
      path_ = "";
      access_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ParseResult(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              path_ = s;
              break;
            }
            case 24: {

              access_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseResult_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 每个excel唯一标识
     * </pre>
     *
     * <code>string uid = 1;</code>
     */
    public com.google.protobuf.ByteString
    getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATH_FIELD_NUMBER = 2;
    private volatile java.lang.Object path_;
    /**
     * <pre>
     * 结果json文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 结果json文件路径
     * </pre>
     *
     * <code>string path = 2;</code>
     */
    public com.google.protobuf.ByteString
    getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESS_FIELD_NUMBER = 3;
    private int access_;
    /**
     * <pre>
     * 预留参数: 文件地址的访问形式
     * </pre>
     *
     * <code>int32 access = 3;</code>
     */
    public int getAccess() {
      return access_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uid_);
      }
      if (!getPathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, path_);
      }
      if (access_ != 0) {
        output.writeInt32(3, access_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uid_);
      }
      if (!getPathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, path_);
      }
      if (access_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, access_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult)) {
        return super.equals(obj);
      }
      com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult other = (com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult) obj;

      boolean result = true;
      result = result && getUid()
              .equals(other.getUid());
      result = result && getPath()
              .equals(other.getPath());
      result = result && (getAccess()
              == other.getAccess());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + ACCESS_FIELD_NUMBER;
      hash = (53 * hash) + getAccess();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ParseResult}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ParseResult)
            com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseResult_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.Builder.class);
      }

      // Construct using com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uid_ = "";

        path_ = "";

        access_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_ParseResult_descriptor;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult getDefaultInstanceForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.getDefaultInstance();
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult build() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult buildPartial() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult result = new com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult(this);
        result.uid_ = uid_;
        result.path_ = path_;
        result.access_ = access_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult) {
          return mergeFrom((com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult other) {
        if (other == com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult.getDefaultInstance()) return this;
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          onChanged();
        }
        if (other.getAccess() != 0) {
          setAccess(other.getAccess());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public com.google.protobuf.ByteString
      getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUid(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder clearUid() {

        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 每个excel唯一标识
       * </pre>
       *
       * <code>string uid = 1;</code>
       */
      public Builder setUidBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        uid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object path_ = "";
      /**
       * <pre>
       * 结果json文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 结果json文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public com.google.protobuf.ByteString
      getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 结果json文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPath(
              java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        path_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 结果json文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder clearPath() {

        path_ = getDefaultInstance().getPath();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 结果json文件路径
       * </pre>
       *
       * <code>string path = 2;</code>
       */
      public Builder setPathBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        path_ = value;
        onChanged();
        return this;
      }

      private int access_ ;
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 3;</code>
       */
      public int getAccess() {
        return access_;
      }
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 3;</code>
       */
      public Builder setAccess(int value) {

        access_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 预留参数: 文件地址的访问形式
       * </pre>
       *
       * <code>int32 access = 3;</code>
       */
      public Builder clearAccess() {

        access_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ParseResult)
    }

    // @@protoc_insertion_point(class_scope:ParseResult)
    private static final com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult();
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ParseResult>
            PARSER = new com.google.protobuf.AbstractParser<ParseResult>() {
      public ParseResult parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ParseResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ParseResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ParseResult> getParserForType() {
      return PARSER;
    }

    public com.attackt.logivisual.protobuf.ExcelFileTransfer.ParseResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RogerOrBuilder extends
          // @@protoc_insertion_point(interface_extends:Roger)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 恒为1,表示找到该文件
     * </pre>
     *
     * <code>int32 msg = 1;</code>
     */
    int getMsg();
  }
  /**
   * Protobuf type {@code Roger}
   */
  public  static final class Roger extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:Roger)
          RogerOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use Roger.newBuilder() to construct.
    private Roger(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Roger() {
      msg_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Roger(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              msg_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_Roger_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_Roger_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.Builder.class);
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private int msg_;
    /**
     * <pre>
     * 恒为1,表示找到该文件
     * </pre>
     *
     * <code>int32 msg = 1;</code>
     */
    public int getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (msg_ != 0) {
        output.writeInt32(1, msg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msg_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(1, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger)) {
        return super.equals(obj);
      }
      com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger other = (com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger) obj;

      boolean result = true;
      result = result && (getMsg()
              == other.getMsg());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Roger}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:Roger)
            com.attackt.logivisual.protobuf.ExcelFileTransfer.RogerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_Roger_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_Roger_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.class, com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.Builder.class);
      }

      // Construct using com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msg_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.internal_static_Roger_descriptor;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger getDefaultInstanceForType() {
        return com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.getDefaultInstance();
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger build() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger buildPartial() {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger result = new com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger(this);
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger) {
          return mergeFrom((com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger other) {
        if (other == com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger.getDefaultInstance()) return this;
        if (other.getMsg() != 0) {
          setMsg(other.getMsg());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int msg_ ;
      /**
       * <pre>
       * 恒为1,表示找到该文件
       * </pre>
       *
       * <code>int32 msg = 1;</code>
       */
      public int getMsg() {
        return msg_;
      }
      /**
       * <pre>
       * 恒为1,表示找到该文件
       * </pre>
       *
       * <code>int32 msg = 1;</code>
       */
      public Builder setMsg(int value) {

        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 恒为1,表示找到该文件
       * </pre>
       *
       * <code>int32 msg = 1;</code>
       */
      public Builder clearMsg() {

        msg_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Roger)
    }

    // @@protoc_insertion_point(class_scope:Roger)
    private static final com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger();
    }

    public static com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Roger>
            PARSER = new com.google.protobuf.AbstractParser<Roger>() {
      public Roger parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new Roger(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Roger> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Roger> getParserForType() {
      return PARSER;
    }

    public com.attackt.logivisual.protobuf.ExcelFileTransfer.Roger getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_UID_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_UID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_ParseRequest_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_ParseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_ParseResult_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_ParseResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_Roger_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_Roger_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\035proto/ExcelFileTransfer.proto\"\022\n\003UID\022\013" +
                    "\n\003uid\030\001 \001(\t\"K\n\014ParseRequest\022\013\n\003uid\030\001 \001(\t" +
                    "\022\014\n\004path\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\016\n\006acce" +
                    "ss\030\004 \001(\005\"8\n\013ParseResult\022\013\n\003uid\030\001 \001(\t\022\014\n\004" +
                    "path\030\002 \001(\t\022\016\n\006access\030\003 \001(\005\"\024\n\005Roger\022\013\n\003m" +
                    "sg\030\001 \001(\0052\311\001\n\013ExcelParser\022 \n\005Parse\022\r.Pars" +
                    "eRequest\032\006.Roger\"\000\022(\n\016AddQuoteResult\022\014.P" +
                    "arseResult\032\006.Roger\"\000\022&\n\016GetQuoteResult\022\004" +
                    ".UID\032\014.ParseResult\"\000\022#\n\tAddResult\022\014.Pars" +
                    "eResult\032\006.Roger\"\000\022!\n\tGetResult\022\004.UID\032\014.P" +
                    "arseResult\"\00023\n\017ExcelQuoteParse\022 \n\005Parse" +
                    "\022\r.ParseRequest\032\006.Roger\"\000B!\n\037com.attackt" +
                    ".logivisual.protobufb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_UID_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_UID_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_UID_descriptor,
            new java.lang.String[] { "Uid", });
    internal_static_ParseRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
    internal_static_ParseRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ParseRequest_descriptor,
            new java.lang.String[] { "Uid", "Path", "Password", "Access", });
    internal_static_ParseResult_descriptor =
            getDescriptor().getMessageTypes().get(2);
    internal_static_ParseResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ParseResult_descriptor,
            new java.lang.String[] { "Uid", "Path", "Access", });
    internal_static_Roger_descriptor =
            getDescriptor().getMessageTypes().get(3);
    internal_static_Roger_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_Roger_descriptor,
            new java.lang.String[] { "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
