# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # for now verify JDK 8 and 11
        java: [ 17, 21 ]

    name: Java ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v5

    - name: Setup java ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Set up Ant
      id: setup-ant
      run: |
        wget https://dist.apache.org/repos/dist/release/ant//binaries/apache-ant-1.10.17-bin.tar.gz
        tar --exclude=apache-ant-1.10.17/manual -xzvf apache-ant-1.10.17-bin.tar.gz
        ANT_HOME=`pwd`/apache-ant-1.10.17 apache-ant-1.10.17/bin/ant -version

    - name: Cache downloaded third-party libraries
      uses: actions/cache@v4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: lib
        # An explicit key for restoring and saving the cache
        key: poi-third-party-libs

    - name: Build with Ant
      run: ANT_HOME=`pwd`/apache-ant-1.10.17 apache-ant-1.10.17/bin/ant clean jenkins
