
# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-ant

name: Java CI with Ant

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        # for now verify JDK 8 and 11
        java: [ 8, 11.0.x ]

    name: Java ${{ matrix.java }} build
    steps:
      - uses: actions/checkout@v2

      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Ant
        id: setup-ant
        run: |
          wget https://www.apache.org/dist/ant/binaries/apache-ant-1.10.9-bin.tar.gz
          tar --exclude=apache-ant-1.10.9/manual -xzvf apache-ant-1.10.9-bin.tar.gz
          ANT_HOME=`pwd`/apache-ant-1.10.9 apache-ant-1.10.9/bin/ant -version

      - name: Cache downloaded third-party libraries
        uses: actions/cache@v2.1.3
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: lib
          # An explicit key for restoring and saving the cache
          key: poi-third-party-libs

      - name: Fetch site via SVN
        id: setup-doc-site
        run: |
          svn co https://svn.apache.org/repos/asf/poi/site/src/documentation src/documentation

      - name: Build with Ant
        run: ANT_HOME=`pwd`/apache-ant-1.10.9 apache-ant-1.10.9/bin/ant clean jenkins
